# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1412350912);
user_pref("app.update.lastUpdateTime.background-update-timer", 1412351152);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1412351032);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1412937577);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1412937697);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.lastDir", "/home/debianito/Desktop");
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.feeds.showFirstRunUI", false);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20140722231038");
user_pref("browser.startup.homepage_override.mstone", "24.7.0");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1407854220424");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1407767820424");
user_pref("datareporting.sessions.current.activeTicks", 24);
user_pref("datareporting.sessions.current.firstPaint", 2423);
user_pref("datareporting.sessions.current.main", 543);
user_pref("datareporting.sessions.current.sessionRestored", 2656);
user_pref("datareporting.sessions.current.startTime", "1412942090653");
user_pref("datareporting.sessions.current.totalTime", 118);
user_pref("datareporting.sessions.currentIndex", 9);
user_pref("datareporting.sessions.previous.7", "{\"s\":1412350550921,\"a\":437,\"t\":4163,\"c\":true,\"m\":809,\"fp\":2813,\"sr\":2878}");
user_pref("datareporting.sessions.previous.8", "{\"s\":1412937455883,\"a\":27,\"t\":326,\"c\":false,\"m\":620,\"fp\":2605,\"sr\":2670}");
user_pref("datareporting.sessions.prunedIndex", 6);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 7);
user_pref("extensions.blocklist.pingCountVersion", 7);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.7.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1407766708000,\"rdfTime\":1406073704000}}}]");
user_pref("extensions.lastAppVersion", "24.7.0");
user_pref("extensions.lastPlatformVersion", "24.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20140722231038");
user_pref("gecko.mstone", "24.7.0");
user_pref("idle.lastDailyNotification", 1412937586);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1412353117);
user_pref("places.history.expiration.transient_current_max_pages", 26292);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1412353117);
user_pref("toolkit.startup.last_success", 1412942091);
user_pref("toolkit.telemetry.previousBuildID", "20140723000133");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1413127290);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
