# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1409327389);
user_pref("app.update.lastUpdateTime.background-update-timer", 1409327629);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1409327509);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1409330749);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1409327269);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.lastDir", "/home/debianito");
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 2714);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20140722231038");
user_pref("browser.startup.homepage_override.mstone", "24.7.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4,\"bookmarks\":3}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1407854220424");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1407767820424");
user_pref("datareporting.sessions.current.activeTicks", 846);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2333);
user_pref("datareporting.sessions.current.main", 552);
user_pref("datareporting.sessions.current.sessionRestored", 2399);
user_pref("datareporting.sessions.current.startTime", "1409327027982");
user_pref("datareporting.sessions.current.totalTime", 7307);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.prunedIndex", 1);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:24.7.0");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1407766708000,\"rdfTime\":1406073704000}}}]");
user_pref("extensions.lastAppVersion", "24.7.0");
user_pref("extensions.lastPlatformVersion", "24.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20140722231038");
user_pref("gecko.mstone", "24.7.0");
user_pref("idle.lastDailyNotification", 1409327254);
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1409327254);
user_pref("places.history.expiration.transient_current_max_pages", 26292);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1409327254);
user_pref("toolkit.startup.last_success", 1409327028);
user_pref("toolkit.telemetry.previousBuildID", "20140723000133");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1410359824);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
